apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: otus-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otus-lab-app
  template:
    metadata:
      labels:
        app: otus-lab-app
    spec:
      containers:
        - name: otus-lab
          image: vyegres/otus-lab:v2
          ports:
            - name: web
              containerPort: 8000
